### ISSUE TITLE
Tazavesh Streets Total Forces Value needs updating

### ISSUE THREAD

**Issue by DrTobogganMD** [Wotuu/keystone.guru#1062]
Tazavesh Streets Total Forces needs updating to match newest hotfixed values

**Comment by omicron-o** [comment]
Adding the changelog from https://worldofwarcraft.com/en-gb/news/23770463/hotfixes-april-8-2022 here:
> Tazavesh: Streets of Wonder
> - [With realm restarts] Adjusted the placement and composition of non-boss enemies in several locations. Total enemy forces required to complete the dungeon on Mythic+ difficulty has been reduced accordingly.
>   - *Developers’ note: We are aware of the length and difficulty of Tazavesh: Streets of Wonder, our changes aim to reduce the completion time of the dungeon and reduce the difficulty of several non-boss encounters.*
> - Armored Overseer health reduced by 20%.
> - Overloaded Mailemental health reduced by 25%.
> - Overloaded Mailemental's Expedited Zone persists for 15 seconds (was 10 seconds).
> - Carrying goods while in the market no longer prevents the holder from using abilities.
> - Veteran Sparkcaster's Hyperlight Salvo damage reduced by 20%.
> - Reduced the total number of bolts fired by Veteran Sparkcaster's Hyperlight Salvo.
> - Cartel Wiseguy's Hyperlight Bolt damage reduced by 20%.
> - Cartel Skulker's Quickblade damage reduced 40%.
> -  Myza's Oasis
>    - Fixed an issue causing players to be able to leave the stage.

**Comment by omicron-o** [comment]
I have updated the group compositions of the first room in the mapping tool. Will continue if I can get into a key.

**Comment by Wotuu** [comment]
The health values were already adjusted and so were a few enemies but turns out not enough. This should be fixed now though - I'm going to push a fix live. Thanks to @omicron-o and Doug for helping out there and correcting the mapping!

**Comment by omicron-o** [comment]
I have updated the count of gatewarden zo'mazz in the mapping tool. Reviewing some other pulls too. Will update my comment if more changes are added.
