### ISSUE TITLE
Route pull numbers not matching original version

### ISSUE THREAD

**Issue by dezmathio** [Wotuu/keystone.guru#1346]
I made a route on keystone guru and when I eventually made it public to share with a friend it showed pull numbers repeating instead of sequential. There were also some errors about mob types not matching. Here’s the url https://keystone.guru/zioYYXx

**Comment by Wotuu** [comment]
Hey, this seems kinda similar to #757  but I must say I haven't seen it like this before. I've cloned the route at https://keystone.guru/route/tazavesh-streets-of-wonder/oiBH9Oq/downtown-skip-city-clone/ (for my own reference) and I'll check this out later. There's just some weird things going on with the pull indices sometimes..
