### ISSUE TITLE
Drawings and notes on different floors will appear on the main floor after import

### ISSUE THREAD

**Issue by andrei-cb** [Wotuu/keystone.guru#1546]
Website:

<img width="1256" alt="image" src="https://user-images.githubusercontent.com/5099150/210168706-4ed3ca0d-e15d-4e72-82f3-9d8cd51e0ed4.png">

In-game:
<img width="904" alt="image" src="https://user-images.githubusercontent.com/5099150/210168716-66a5bcd8-6991-402c-b4fe-2f53414d48ca.png">
<img width="902" alt="image" src="https://user-images.githubusercontent.com/5099150/210168722-bb4bcbb7-8ac5-4dd7-8daa-74ee872058dc.png">

**Comment by Wotuu** [comment]
Hi Andrei, thanks for reporting this! I just fixed this issue in the dev branch and it'll be fixed as soon as I push a release (won't be too long).
