### ISSUE TITLE
Ulduar maps?

### ISSUE THREAD

**Issue by camille-hdl** [Wotuu/keystone.guru#1553]
Hello,

Thank you for your work on keystone.guru!  
I recently discovered that you have wotlk maps on the app. Do you plan on supporting Ulduar when phase 2 launches? (I believe next week)

Cheers

**Comment by Wotuu** [comment]
Hey! Sorry I missed this one. Someone happened to inquire about it here as well yesterday: https://discord.com/channels/482454450754289675/482454451316195339/1068274004017807491. It's in the works!

**Comment by Wotuu** [comment]
I just added the Ulduar mapping: https://github.com/Wotuu/keystone.guru/pull/1566 will push this live as soon as I can. Probably not today but tomorrow.

**Comment by camille-hdl** [comment]
Thank you for your work! I'll check the website to tell my guild as soon as it's live 😊

 Cheers

**Comment by Wotuu** [comment]
Heya, this is now ready to release. Just need to rest it on staging tomorrow and I'll push it live when I did so. Bedtime first now!
