### ISSUE TITLE
I cannot switch my login battlenet account

### ISSUE THREAD

**Issue by fingershi** [Wotuu/keystone.guru#1637]
After I logined with one of my battlenet account, the website / browser seemes recorded it and automaticlly login with this one whenever I choose to login with battlenet account. I have no way to change to another bn account.

**Comment by Wotuu** [comment]
Hey, sorry it took this long to get back to you. I just tried the behaviour myself and reached the following. If you've given Keystone.guru permission to access your account once before, it will remember that and automatically log you in to Keystone.guru based on the current account that you're logged in with to Battle.net.

If you want to change Battle.net accounts, you should log in with your new account on Battle.net, and then simply try to login with Battle.net on Keystone.guru. It should prompt you again for permission, you can grant it, and it will register a _new Keystone.guru account_ for your new Battle.net account.

If you want to transfer Keystone.guru data from your first account to your second account I may be able to assist - though we'd need to ensure your ownership of both accounts before I go messing around with it.
