### ISSUE TITLE
Enemy Forces Values for NPCs Appears to Be Wrong in Some Cases

### ISSUE THREAD

**Issue by blorticus** [Wotuu/keystone.guru#288]
I have been building a route map in Atal'Dazar, and it appears that the Enemy Forces values for a number of the NPCs is incorrect.  For example, a Toxic Saurid is 0.5, rather than 1.  I based this on values provided by [Method Dungeon Tools](https://wago.io/mdt).  Those values appear to be accurate.

I would be happy to alter the seed values in this repo and generate a pull request with rectifications for the various instances, if that makes sense.

**Comment by Wotuu** [comment]
Hi,

Yes that would work! Though of course I can do that for you too. I'm not aware of any enemy giving you 0.5 enemy forces, I'll have to give that a look in MDT. Are there any other values that may be incorrect? I'd of course like to have a accurate mapping and that includes enemy forces :)

**Comment by blorticus** [comment]
Alright, I feel like a knuckle-head.  I didn’t realize that “enemy forces” != “percentage”.  That’s true in MDT, too, but the output shows both and I mentally merged them.  Feel free to close this request.

**Comment by Wotuu** [comment]
I was just going to say that it seems correct when I mapped the route I always run in Atal'Dazar :) 
![image](https://user-images.githubusercontent.com/811809/82078357-4d7bfa00-96e1-11ea-993a-b2e17535fdce.png)
No worries! Thanks for reaching out regardless! If you have anything else (from bugs to feature requests) don't hesitate to let me know about them.
