### ISSUE TITLE
Integration with Method Dungeon Tools

### ISSUE THREAD

**Issue by Wotuu** [Wotuu/keystone.guru#32]
Being able to export from Keystone.guru to MDT would be great. Do some research about how to generate a working string to import in MDT. Also perhaps contact the author(s) of MDT and see if there's some option for collaboration?

**Comment by BlackFayah** [comment]
In case they don't want to collaborate, this is where the magic happens: https://github.com/nnogga/MethodDungeonTools/blob/master/Transmission.lua. They serialize > compress > encode.

**Comment by Wotuu** [comment]
Thank you! I'll have to dive in when the time is right, first I'd have to install MDT myself and see how it works and how I can translate Keystone.guru data to MDT data. I don't think it'd be too hard, but as always, it's some work to get right.

**Comment by Wotuu** [comment]
I'm likely going to pick this up next.

**Comment by Wotuu** [comment]
This will be a general research ticket where I will analyse the structure of MDT strings and make issues out of the process.

**Comment by Wotuu** [comment]
I just added a bunch of new issues. Moving this to long term, but it can probably be closed.
