### ISSUE TITLE
Co-operative real-time editing of routes.

### ISSUE THREAD

**Issue by Wotuu** [Wotuu/keystone.guru#37]
Using some real-time technologies, it would be great to collaborate with multiple people on creating one route. There's multiple technologies that could possibly be used for this, such as Signalr and likewise (Forced). I'm thinking of Vue since that's work relevant, but I gotta read up on that first.

Once I got the real-time bit going of the frameworks I actually do not think it'll be that much work. The JS back-end is quite OK done and I think it can be expanded easily.

Ticket for the future; it's a nice to have but low priority for now.

**Comment by forced1988** [comment]
https://laravel.com/docs/5.3/broadcasting#installing-laravel-echo

**Comment by Wotuu** [comment]
I've received some extra time at work to explore Laravel Echo. I'll be using this issue to start experimenting a bit and toy around.

**Comment by Wotuu** [comment]
Live as of v2.5.
