### ISSUE TITLE
Infested affix support

### ISSUE THREAD

**Issue by Wotuu** [Wotuu/keystone.guru#39]
I wanted to include this for launch, until I saw that the Infested mobs change every week and thus cannot be mapped traditionally.

I was thinking about adding a voting system where people can vote a mob yes/no as being Infested this week. Min amount of votes something like 2-3, if there's that amount of votes the mob is marked as Infested. No votes to allow incorrectly marked mobs as Infested as non-infested again if the amount of No votes is higher than the amount of Yes votes.

Any other ideas perhaps? This is something I want to work on sooner rather than later.

**Comment by BlackFayah** [comment]
Should be a good solution. Another option, which is more accurate but also requires more work to get it to work, is to write a small addon that scans mobs inside a dungeon to look for that Spell ID. Definitely would go for your suggestion first.
