### ISSUE TITLE
Error 500 on import of MDT string.

### ISSUE THREAD

**Issue by savenelson** [Wotuu/keystone.guru#462]
Key is
 `!1zvtVnUnq0FoBp0ei(LO4X9dSa72I0c4Th6fctBrfRgzXajQKn9G(T3ziLOPCCdmCSiN5nV5nZisnr)d9UJUo3WFA6SEV9B9noCnZK39zC92(h1F6kBQ)P(bU2R35T)e(MFpzE)h)Y8(dVnV)ldgFVBuV7CDlc0b7JtTDikpq07AgS2tUU6V7A7T16dxwb3gWAQTwV73oPo)xMp)TYAaNxmDt2anNggS9()CQRt)aLKwy30Ho7l2UqagAB8)rtZO1pc(8aj8vjHYdz6B6VENuvuuOyQsIqqkeL6M74C9UFQ)AfVsvWLkjtYklyfXD8laWsai4WcvuszLQsP4OzLraklecPSawUsq5YvaaiQseHNWbIchycPuWuePiNimzfVqYivffvvL)Feb2UKjKqEO4eEoreswbrjOfYYsb4XfIite5cofq6WkysvPSsjZXHsysUc(dqICnrYYejHikqDLaqWYZeAvfNlLCbLc62fI4t1VVm1)O11h6QicSPYEEPRB02zp6BD9XAjw1b)Eg6aYQUl7HBJF84xRl5x6CH(SgMTPjarCtwupc2s5RbiZd0ELfwtMbNhDmlQSqu5HFiYJTkZ04o88hkxEGh8Nf(S(4wsZqkWYrnLcQiH4PHyK0QqAEfNf5CUmet5M40CiehAIwze(I9xcnzb4YnXg5BOignQk0QScdJgZ1yYY4rzJK3wkssuuv9zuIuSbnQkwVLXAqvu7kd(YcMMeTRBdGIAAImxNUKDHseP6g(J5iQVe1ghz3MKSQykxgtzzmLfXuwLjDqN2HnsxSBwf7l2ckj2ZrI9nKOosIQgzbBWL86YsRF52McsmDt4gjljswArexze3qJxIDLzkIHeQ6(aJYXJgZbAC4GkIviAS6Y0VF0mb)vTAltQKOitsgHOxQxM5svu8)pqxNgj3GXRd28OBxkEKSSyfg5sW5BQwXXsY1cQq)(jXuwflB0ftl3Ov8L9wEtapisc9vDxBF1qyK1Rx6HZBwJL)B16gynnbxmIl9Ix6MPzI2LbbYnJW1VUsL)AKOIQYm9s0x1mL(hVB6Ik2AeTqFJzf2vgr03ONxMhCAXM8KVbGWzsUd)dCIt60LD94Xq1XhHJvlljCIOsjeC(6vhaO)6DvefCEofUwHurPYL7oKER(NWQ5UFFA0pV3FQDCEpEi2VIpy7N3pnAN3)MBAyE)O9ORVEEFxWwhS5rhC9i3RWV8U59NmVKSfqAamTXb)UZG2FWnoEVoDW2v0hUvrfCNbcLbCvwLrF48zcHwrkiYcjCtG4vaUI(FSXBhw5pgjG)p7g8Mo4rZXNIe8CB9AA9i8yt7JNaI93M)9SzE)VeDEWn5HSOT)y3uTDCXk4q)GNaADUdis9TyyM3)AR)eK6y0VdCRjiaFaIdCzZWQ9oig1o0DJpjROrDa56T26i5A7h9wt9Qmo6od38WgRgyoHHX1e8hlj1o8ULG1UEuJFCYG69Ja9Fgz1P2UCqSDOpg4clVy8ywfYf3bBx74tODbgbfudWTXNnyj1G16fnkl1pyHIQfvWOOGUIk49ZFF(7p4goB66GlB)nyRH3I7BEXHk)zZtbx(XBdM((2JyXji3JrXjfnZRMNS9OWaFFU1MKzlsju3Tyb(WKpO82q0ASwaVU2NWQN)dJXS6vOj4eUWs(eQgEh(hOHTnnThN683VoJ9Q1(e2yTlT1B64HC6)7p`

**Comment by Wotuu** [comment]
Hey, thank you for the report. I'll check it out now and see what's wrong!

**Comment by Wotuu** [comment]
Closing this, will continue on #463 !
