### ISSUE TITLE
Import from MDT string error

### ISSUE THREAD

**Issue by abighairyspider** [Wotuu/keystone.guru#509]
Just found a link to this site on reddit and thought I'd give it a try, but the first MDT string import I tried gives an error.

`!LUz3UrYnsw4NilN8FYB9UyawVl6DaKhS3vqsTk5UwxTQgsLShFJE2xgNtqYOK6Tng0Jn8u9xuvEyYmy8dz27C7(LDx)Xthp90F)2J7pFE))XJpCsy3(Y5t)Bc)WJ)6UF6nFN7)N7(qC35DxFE))S)F)LN2F84R38H)NxV5UBF(WhF9MNo9Y597U(Z3FqUwp80(9F60X7)5thEC)97UB313T)xF5Wr5s)b3YU8h6xUxoC)UR)VU73)5pS)F8W(NFE31)(ThFzVCLEE)X9F88Htp2)d9VmheF8LNEA)JNV(L7oU)33FexYV8YXJpZV06)0)6FWJpeWhI4dj5FplGFXyB8HZY)pnG)qu)dyKIjL(4)HW(hEyCnguH12VUU5l1S)Hc(GJ2Q4p3WhCB4torX1aqfUWXxDONzesjs2Xz8nJZW(H114SjJ(540PZsb5lwm3UNLlTDKG5ezGg4qoIHmUNcxi7d3rzZx8ZvDY83N(k3pv8nkMRLmPYRvzCTmp6gZn2lPZzUfKHP9p5NpA5Z8lNRAqO6BEMoMRol36Mlw9YPQM5N1DeKzazA5R8dGFLlE5phd0LSWbB97d6q(88oC8vV1HjiX)WohMFNppDxMEHvoppVLI2rywfYFX90Bgtr7ppy)5j9Nh29(vhT53HdZZMjJlx2IlPB5qoMbwptd7ENV(6rCE6lj)K0U3VaW1EZJGlCx9x6Dax6p49Vz4itUbmIZ4EQyMLR4FB4FP3(M1dW7EJ8LlKNxEF4IFy4IFOF37wOi)aJlx28nfjQxibNN9PDVBzW8hsbViI4CWe1lA7Il6gUODO9R6EZivJEcZE7kbz08(FIUEACV)2Lj(8fxH36YWNryS6TE0JLo(6)p)Gp4FJhcNicxetj4(Qd4zgIld9Yfbb)fx3voT)9xE8x3F6rKWnKK8T7)SK18U534V3t0jt9x)0Hho)F)WdpV)8mVNETU)WdpC4JVC88FUtC8V(p2V)3KVW1NU7)TNnD(1V(i)01PM)k4lC9p4sHRkYD)1PA7QkucqN4dpG5fSiW8viHMaDxHuedyFT6K6ePQHRyAJoo2UI5oM4Obd52UsYlc9IfGllC1GfjlfCBajJjzG6DlS3Gfjlr5o1hv8g89M4SblswCImEkzqK33M4W2chejZvrYGxX9lsiSWrdwKmNWfHsIhfHYcxnyrYSxM3JushEg5wyVblsMGKXOILVsAHZgSizkIFiLCtMiITjoTTWjrY02vsUfVILphw4Obls2NmLyKqYqtCisLfUAWIK8widjdyWMDlS3Gfj1pcjdf5XqoTWzdwKmeXhRkUpjNBtCzBHlIKbNClu8gCyHJgSiPVitpLSbxwyJKfrsFqUHRgjRUf2izvK0vXhhs2LVMw4Sbls6sIK1HK9hX12e32w4MiPZlxKgLmlteTWchnyrYTgUizdUSWvdwKCdUpUTT1i0T5mg8wdISBEzXHBZm762sgdzRHU0XwfHy2g3Uf5p0wgCBgdsKOylk38oN3AiymeTgsIHnAW4p5CfJHQ1GiEfHBC(nJbjM00G3AqeV6z8XO6HlxxjU00q2AqeVu5LQAn0wgcBgds0PypeNmthmRICs8PPHO1GiEUXppehx3IXq1AqeVh8s0JHPc8BjXPMg8wdI4jKAXfnXnCsSQPHS1GiEsVuJiKINHeVAyqdyrdseRyYZulE1GCDtbJHO1GiEpzeUuuC6ziXTMgQwdI4XmgH5rAi0GIZyWBniI31dz5O4CzqozmKTgeX7ZBWafVrdTLbgetnirXIbkodJP5JL4ytdrRbr8qGgyYEpwgukgdvRbi(gMez4SEodj)F1zm4TgeX9v8SHH0szmjkX0MgYwdI4EgYGH16zXqDaTLbgytnir2IEKEZXqB9SKYyVfmgIwdI49aQYiKH3YC4kX3MgQwdTPbpJWLl8p4mg8wdI4Um)meVSjt7(TKXq2AaIhrfimcxjWsDAldmcNAar4CSofgHRBOIQdNvVJ60LPGGc(juJ32wmivv3hf)a6s8N0IFTLmg3YZsg5eryc58zvlzuH5fSq4OKXctXmH69bxqcPkWPK3fzgVzHJgCIy5JC6JHxklC1GBe3gLmw1PUf2BWqseGJXM713QLmoWzdgpWmLmwH7fcl7mLmsmck7qiegtUh5UWsgh4ObdVeK5MXJljCrklC1GXAdS(lAMyrOyf7nySUasghEMzwY4aNnySGe1iZyWDC87YhlCPpgkdcdVgEKfiCJ(y9fstFmaZliEKJkIRaMN(yacFmLsFmglq0QVqIzbx4Ob3LlWrd8X8UadaUWvdUj4cCpGKU6WhBG9gCqW5PpM3JGR(0cNnyijQMd(y((tcTTefdFmfhGKCLkK03g(ydC0GHKsed6J5dyrqOSWvdUrSx9X8SGMOBH9gmKe3cWhZZ0TX0cNn4cXb1hZhrqIyBIrwEfNCe702s8jeanfw4ObVKe539ju)tQSWvdEDxIC7(ewSLx3LzVbRtSETTeFg1iMtlC2G1NLbTTeFomAlrXiJUIlo6qK12s8zuRDjSWrdgswNTL4lOdUszHRgmwKSnBlXJ8gOTKb2BWbUKkOTL4zV2ifUIZgmwvgLLQi)TVIBEK(MyK9wXi59g7wbswXkBK6wXrdondBJ82(kkAOvw4QbJaXCxe2OMCthysB1G3AabJzHHiPTVPrssgdzRbeqoZ(vG2nwwktAtdmqKAGjTB0aeVXCCiw0Wq0AabM9iTjdhXNOSTKHHQ1qJXSNTLe4tv2wI30wY0aQsKD4GWsHnKbJTLmmKTgqvIr2Vsfgq8z2wIAiSzmGmGbD7GO4rAiymeTgq9XyHeBlrmGVvXyOAnOfNlZcXn1a(doJbV1akoxlZion89KGlErcUe2dbZtA0kcepQpb2ycocZli6)b13pMG9mbhHUTffUv5WSiQWwAMGtXrdg97rVtQhNaklC1GrVEUzruHnuIhCMuS3GX93kbxWTnlIkTsWnWfEJVPj4co3SikIPpeXWfkTntWfCW7hoqkoAWAVDfnbxaRG)EEYIty4r5Ot1lXFlxcPES(w3RjvI9H9d)qex2)2pKBLU)yVRZuAlK6oD00Lk98VD4lVEZFC48NE9MNV9l)4Hp)LNo88Ph)XpF4X77OtNo)P9)4Hh)9dp)6p)6p)LNoD3T3D8p7)Ktpj)MZNE9M73Fl(54s9PtpU)5Zh)toGZVBaxZXqF9JV1xO2hBoZaoL7HT6Ds0lXlKR91yDtP3oG)p)ZNoC7JVEZVE64(ptrkVtKUtFFfxAR36BULIywjmMvcLAQ3)y3vm16Xm)AZkFfrQVtKuVV0TEfwTyT27cSAePK7se9HyFQ3lXF)A3jF8t3EORXHhE9Mh3V)(93VBDgFxoL1k9qGTCxWTC)FSpJlHAYNB5T()tAt8Rj0FC7HZ9NuhKZt)l3E(PthF(1BU9P9DT76FRCBEsEw)LtN5du5GU3zoXWrSejn4MwSCVNCglXxXsqUVcnnwIcZlyrGBZgYImf5eYgYivIL4zFi6E4hgXsg4OblYv4p0U7nLfUAWIK96kYASeDV38Uf2BWqYTvdzHzdzdC2GfjZyRa1nkdDZiXsuSUnzSDlrYm2HgDtYM7H)ahnyrYm6Fs3Gm3OHSbUAWIKjSnnSHmppNf3c7nyrswrjBiZJjzPy5boBWIK8eCydzDCGflRyULyeNGKUzXYdCyHJgSizKD1Nn4YcBKukwwQjVo2dFG)EIV6U4iR80hNd7G2BOpIZpGd64WDNW8cIrCA6U7X2(3Mq6UtkC31TdKAXk1clC0GHCBZuNcoRU7kUAWqsUQLsYnDWTWEdomhG0DV7FKv3DfNny9Psy6U7MU7eRU7UP7oFIRU7ZuNdC0Gt0BkmD3LTz676rR)9zjkH()RxqDS2Z60RR2KkY1Q9kI7lvB5qS32XxlU69hE(ZhEUhl9lY5JAEDeM1E1RAOqhizFqQWbsHYnRSvkATxeMxWYewb0Roqkeoqk1PsLuhO4g3G2WchnyihgnWbs2rScDGg4QbRnXmCGKDbrDGgyVbJ(MqycpLKbjtlC2G1(MM1EP7wrBIzTxeh0w1gXlLEw14LdC0GHKOWtw7vJ5RklC1GBCNvgXldvu1g3CHv8Ybw7bUPXldv(50cNn4c7gFtJxgQ88pBtCABH5Ml4KGnjkjgSCZfioAWIKvSZGjkjECJnxqXvdwKKhkuMsIuIyZfuS3GfjzcFS5cHcJXLw4SbdjXE9HnxOxKLS2eBUaXyZfum2CHcpIsizHhDzyHJgSijpY8s2GllC1GfjlO8J62cxDlSrszZf6fBIpAKu2CHb2iPS5cHmpS0LKMWsP)LdlDrZA96IXkaCPzEFbI1zrfgX1tH5fuhABAZACVtAtiBwJujGriJQDyZAL0yhVh4ObJ5c3mJtOWo0klC1GBeN0agbEcHy3ivS3GHKiniBwJV1fy3ivC2G17XYiGrfjl8TjMbmig7gzUTcyG1mFxpSsx8WAJdq5sh8A5bs7Wr9HLVnEyryEbLBK1whhyY62eYhwAkCi12QZA9iLclC0GLeNnEYuSNtuFekpqXvdUrSB8WINeakpqXEdwYv34l6cBZL9kNw4Sbdjzd3Sz(6OZAfh2wyuEqlplpqNCr5bkoAWjI3gr33qsXqzHRgCBI5wh3Wb)fDlS3GdlCeygVEjj36yfVKKBDmdshxsYTowJD7M38CRJR1r09boAWRjwU1XvSEevdR4QbdjH3f364kAli7wyVbd3h8GIBDCbBPdIUR4SbxwoXqYsEU1XeZToMyeDFZS1XfUJYHfoAWqsur5CRJtA0DfxnyrshsAZTooJhAi6UI9gSiPd7So364Si)3viG8fHa451qfzNxcmmAi2ZiEPjmVGY9NJVjnkSWqao9DuzrriaV50JY(z8AV50JuSiNpmdbiBOFuJxR4Qb34fjQHaKPOGgVwXEdg3FRtO0NrfriETBDcLdmUh5H4YNH(rbEkMNEeXiEDhpIxl(hHVVhwFLDgQ1C9k(ZLTspPsTy3zOCyRS1I9BKMx3pheu)d(LupF(2Nop2WSZF6GStkYgLPBMZTpCE)tVEZVD4O8xeHo(P93k)vl4QxV5F88E5x0)pF84(B)99p9m3SLpT)4x4Vqn)5t398v7wVlTlVT4gMkL5g9aY6q(2yWiv5H3gH5fSmHJaJj6TPVmhBlk82umdfxMEBkoAWl50eoCNWxcQjCiEjjt44zl2ljzchfVKKjC8mN0ssMWrXL1ueKmG4IWBJyMWHy4TfHdot4e5mAyHJgCI48iHtYp2(LbUAWnIBJ2jY4vEj6wyVbdj5BwjKm3gjCg4Sbxw4rzxzTDcIz7eL1zvgxNvPwAuAjP2obXlj12jQJeodC1GvjtJ2jAseAZ6187xVE33E9A7YGRHH7Uu1KwmSdX4O3aFRoNW8cIapBJUNLazQ7oHA9vl39n99BdEQ8n(lSWrdgzR4XsmC31UNh4QbJeK81bM1x5g1xnWEdgsUEJHf5tQ7(26ngEGx5K16R4xzLtwRVcy4UVHA716R2MU7koAWQKn1Dxk3iRU7kUAWqsB9v40sJUf2BWbov1g1xvrjgX0cNnyTmG6O(QkcNb3DIz9veN0Ya2M1xXnKmSWrdELxwRVcLya3DfxnynRvEuFvbfPLDlS3GHKS1ywStEwFLIZgmYndxtT(kjg13o133EPKF7YLsC37ufhlLW7nMPuS0eMxqm0yLva6gTQqiRtHuwNcFHx8kEwNcXrdg1PyElxkSuMYcxnyK5yBUuYZ3JuM5yBUuAGdZlcRtPG6b9ljzDkkgswx1PuLl4)Qt)f70)LBKCTmM(x)DFqkYxtC7s89DFcZlOuSFfLblJmxed42eQNBcFtgDZlGEUj89)CjMEUjeN4aB0wV8gP650)axnyizCwMO(k6JofvS3GHKWNy(sgN50)aNnyrsEWo6gjJIarNI6RJ22cJofl8V2cqs94uclC0Gfjl(zKSX(lxw4Qbdjrn96lvmsrGofvS3GfjZMZnHh(c6umBo3eflsMX7mqCizKrYump3eIrNI892HNBsimsCpWrdwKmHeu6F3hKG0F7Tl)Vi(XfVjMIKv1b2ZDuzkyCbxJI8ck328LBQQqg)qH6jH0gXpKddOmCGd8anclC0Gf54bVOVT88vQPSWvdwKmYZPB8OTPoWk2BWIKXWm(HEkC8KqcZ4hdCHxK4U1b)Luh44Qphfdh44AFPg(1HfoAWysLBV0ynJtDGvC1GXelwFpFR4ZQdSI9gmMyRZT6q(BPZWbwXzdgoWC7nyKHWivSI13f(WivS0qAz4ahJx9xD4CFtxs5F29)b`

**Comment by Wotuu** [comment]
Hey, thanks for the report. I have corrected the issue in the MDT importer. This should go live with the next update, thank you!
