### ISSUE TITLE
MDT String export error

### ISSUE THREAD

**Issue by xingyuz** [Wotuu/keystone.guru#625]
I mapped a route and tried to export it to MDT string, but failed and shows "Invalid MDT string: Undefined index: start(400).
I can export others' routes to MDT strings correctly.

This is my route link: https://keystone.guru/C0UxK05

**Comment by Wotuu** [comment]
Hey! Sorry it took some time to get back to you, I haven't had much time as of late to work on the site. The issue was also reported by someone in Discord and I fixed it right there and then. Can you try again and see if it works now? Thank you for reporting regardless!

**Comment by Wotuu** [comment]
I'm closing the issue. Please feel free to reopen it if you still encounter the issue. Thanks!
