### ISSUE TITLE
Re-ordering or adding new pulls may cause out of order or duplicate pull indices

### ISSUE THREAD

**Issue by Wotuu** [Wotuu/keystone.guru#757]
Context: https://www.reddit.com/r/CompetitiveWoW/comments/ms02yj/keystoneguru_m_routes_made_easy_redesign_many_new/guss9mg

**Comment by Wotuu** [comment]
https://discord.com/channels/482454450754289675/482822434106638346/869923242188615751

**Comment by Wotuu** [comment]
Reproduction steps:
1. Create a pull
2. Create a second pull (I used shift click)
3. Create a third pull at the end of the list (I used new pull)
4. Move pull 3 in between the other 2 pulls
5. Delete this final pull (the one now in the middle)
6. Shift-click to create a new pull
7. Refresh, you should now have 2 pulls with index 3
I don't know if this moving a pull from the end to the middle is a separate bug/interaction but I figured it was worth mentioning

**Comment by omicron-o** [comment]
It seems the minimum you need to do is:

1. Press new pull 3 times
2. Delete the middle pull, index 2
3. Press new pull one more time
4. Refresh the page

it's important that you use press new pull on the final pull add. Alternatively if you _deselect_ the current pull and shift-click to add a new pull at the end it behaves the same. If you shift click while you have a pull selected (even if it's the last pull) it will not trigger the bug.

**Comment by Wotuu** [comment]
@omicron-o I just double checked your reproduction steps and doing exactly that keeps everything in order now. Closing!
