### ISSUE TITLE
Allow better display of Inspired/Tormented/Encrypted enemies

### ISSUE THREAD

**Issue by Wotuu** [Wotuu/keystone.guru#881]
They currently are highlighted with an attribute but this really isn't clear enough and needs to be improved.

**Comment by Bukama** [comment]
Would it be possible to surround the portrait-circle with this inspiring-yellow-flashy-thing?
Or just putting the Inspiriing Icon onto the portrait - even at large (far more out) zooms?

As written in chat, currently you only see the icon when you zoomn in, but then you dont have the full map (on your second screen for example)

**Comment by Wotuu** [comment]
![image](https://user-images.githubusercontent.com/811809/160402306-3177320e-6bd2-4415-9650-a04f3c7df35b.png)

Bit late - but this is how it looks now
