### ISSUE TITLE
Add a "back to my routes" button in the header of a rout

### ISSUE THREAD

**Issue by Bukama** [Wotuu/keystone.guru#913]
From discord: Add a "back to my routes" button in the header of a route, allowing the user to fast get back to the routes overview

> [15:15] omicron: Honestly the most important page is probably the my routes page
> [15:38] Bukama: Yes and i am always search for a short back-to-my-routes in the header when ive opened a route. Always getting remindet to reopen my fav entry or clicking through the accountmenu
> [16:07] Wotuu: Should be a quick win to replace the current home page with the 'my routes' page when you're logged in 👍 I can always refine it later
> [16:07] Wotuu: Maybe add some links at the top that are now found under the dropdown so that you won't have to access that either anymore

With header, speaking of this part of a single route's view.

![myroutes](https://user-images.githubusercontent.com/4354359/140651255-45c9f0f4-f2d7-4348-98a3-ac9d011c46d3.png)

**Comment by Wotuu** [comment]
I'm solving this in ticket https://github.com/Wotuu/keystone.guru/issues/745 :) you can navigate back home and it'll show the routes page there.
