### ISSUE TITLE
Remove Team Members

### ISSUE THREAD

**Issue by alekradev** [Wotuu/keystone.guru#922]
Hi there,

I miss the function as a team leader to remove certain team members. Does this function exist or will it be implemented in the future?

**Comment by Wotuu** [comment]
That's a good one - llet me check and I will add it if it's not there, should be something basic for admins to have indeed!

**Comment by Wotuu** [comment]
So I've labelled this as a bug as the feature was already there (as I thought to be honest), but there was an error in the logic that prevented admins from removing people from the team - only moderators could do it.

Admins can remove anyone now - moderators can remove everyone but admins now as was intended.
